update

diff --git a/0x00-python-hello_world/1-run_inline b/0x00-python-hello_world/1-run_inline
--- a/0x00-python-hello_world/1-run_inline
+++ b/0x00-python-hello_world/1-run_inline
@@ -4,4 +4,15 @@ if [ -z "$PYCODE" ]; then
 	exit 1
 fi
 
-python3 -c "$PYCODE"
+tmpfile=$(mktemp)
+echo "$PYCODE" > "$tmpfile"
+
+pycodestyle --max-line-length=80 "$tmpfile"
+
+if [ $? -eq 0 ]; then
+	python3 -c "$PYCODE"
+else
+	echo "Error: pycodestyle checks failed. Please fix the style issues."
+fi
+
+rm -f "$tmpfile"
